<<<<<<< HEAD
import Activities from "./Activities";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
=======
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Bottomfooter from '@/components/Bottomfooter'


// import Font Awesome CSS

// Tell Font Awesome to skip adding the CSS automatically
// since it's already imported above

// Tell Font Awesome to skip adding the CSS automatically
// since it's already imported above
//config.autoAddCss = false;
>>>>>>> aabdf04c322d458a61ec8c0650952733d9d88340

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Tree++",
  description: "TreePP",
>>>>>>> aabdf04c322d458a61ec8c0650952733d9d88340
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col">
<<<<<<< HEAD
          <Activities />
          {children}
          {/* <BootomSection /> */}
=======
           <Navbar />
           {children}
           <Bottomfooter />
>>>>>>> aabdf04c322d458a61ec8c0650952733d9d88340
        </main>
      </body>
    </html>
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> aabdf04c322d458a61ec8c0650952733d9d88340
